graph_directory: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/development/Tutorial/subgraphs/dot/complete
results_directory: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/development/Tutorial/results
LEXICON: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/development/Tutorial/Tutorial_lexicon.json