graph_directory: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/synthesized/micrograph
results_directory: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/synthesized/micrograph/results
LEXICON: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/synthesized/micrograph/lexicon.json