graph_directory: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/development/Heal_TheCar/subgraphs/dot/complete
results_directory: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/development/Heal_TheCar/results
LEXICON: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/development/Heal_TheCar/Heal_TheCar_lexicon.json