graph_directory: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/development/Heal_TheTrees/subgraphs/dot/complete
results_directory: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/development/Heal_TheTrees/results
LEXICON: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/development/Heal_TheTrees/Heal_TheTrees_lexicon.json