graph_directory: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/synthesized/bitsy_bakery
results_directory: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/synthesized/bitsy_bakery/results
LEXICON: /Users/lizcconrad/Documents/PhD/GP2/GG_project/GG_data/synthesized/bitsy_bakery/lexicon.json